name: Data Tests

on: [push, pull_request]

jobs:
  data_tests:
    name: Data tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [duplicate_entries, missing_values, vote_breakdown_totals]

    env:
      LOG_FILE: ${{ github.workspace }}/${{ matrix.test }}.txt

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Check out data
      uses: actions/checkout@v2.3.4
      with:
        path: data

    - name: Check out data tests
      uses: actions/checkout@v2.3.4
      with:
        repository: openelections/openelections-data-tests
        ref: v1.0.0
        path: data_tests

    - name: Run data tests
      run: python3 ${{ github.workspace }}/data_tests/run_tests.py --log-file=${{ env.LOG_FILE }} ${{ matrix.test }} ${{ github.workspace }}/data

    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.4
      if: failure()
      with:
        name: ${{ matrix.test }}_full_logs
        path: ${{ env.LOG_FILE }}
